# Tomcat
server:
  port: 9204

# Spring
spring:
  application:
    name: zimble-crm
  cloud:
    nacos:
      discovery:
        server-addr: 10.26.245.15:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.26.245.14:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1qaz@WSX

# Mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zimble.crm
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml

security:
  oauth2:
    client:
      client-id: web
      client-secret: 123456
      scope: server
    resource:
      loadBalanced: true
      token-info-uri: http://zimble-auth/oauth/check_token

